export const Favorites = [
  {
    id: 1,
    title: "Wireless Headphones",
    description: "Crystal-clear sound with deep bass and noise canceling.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628874/pngimg.com_-_headphones_PNG101961_oahxry.png",
    alt: "Black wireless headphones with noise cancellation feature",
  },
  {
    id: 2,
    title: "Smartwatch Pro X",
    description: "Track fitness, monitor health, and stay connected.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628875/crossfit-pro-x-smart-watch-195559_1800x_jldssi.webp",
    alt: "Modern smartwatch displaying health and fitness stats",
  },
  {
    id: 3,
    title: "VR Headset Max",
    description: "Immerse in gaming and entertainment like never before.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628872/3d-illustration-of-vr-headset-png_sljxah.webp",
    alt: "Person wearing a virtual reality headset",
  },
  {
    id: 4,
    title: "Smart Home Hub",
    description: "Control your smart devices with voice or app.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628872/pngtree-a-isolated-smart-home-hub-on-white-background-png-image_15836498_w709pi.png",
    alt: "Smart home hub device with digital display and controls",
  },
  {
    id: 5,
    title: "Gaming Mouse Elite",
    description: "Ultra-precise control with customizable RGB lighting.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633065/61YTpIudkeL_icpjvg.jpg",
    alt: "RGB gaming mouse with customizable buttons",
  },
  {
    id: 6,
    title: "Portable Bluetooth Speaker",
    description: "Compact yet powerful — music on the go.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760574927/WhatsApp_Image_2025-10-16_at_01.29.25_1cb40d4e_kjqh39.jpg",
    alt: "Portable Bluetooth speaker playing music outdoors",
  },
  {
    id: 7,
    title: "Smart Glasses Vision",
    description: "Stylish eyewear with camera and notifications.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628872/NJYUAN-V3-Smart-Glasses-4-800x720_n9nfyx.png",
    alt: "Smart glasses with built-in camera and display features",
  },
  {
    id: 8,
    title: "Drone Aerial Pro",
    description: "Capture cinematic aerial shots with GPS precision.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628880/Drone-PNG-Image-Background_se8kxw.png",
    alt: "Professional drone flying over landscape capturing aerial shots",
  },
  {
    id: 9,
    title: "Noise Cancelling Earbuds",
    description: "Pure, immersive sound without distractions.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760574927/WhatsApp_Image_2025-10-16_at_01.29.25_84016980_dizbbg.jpg",
    alt: "Wireless earbuds with active noise cancellation",
  },
  {
    id: 10,
    title: "Smart LED Light Strip",
    description: "Customizable colors to match your mood or music.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629708/e41bf895aae6fa9adfeb14a865f33d5b939e2ccf_c2xbo2.jpg",
    alt: "Smart LED light strip glowing in multiple colors",
  },
];
