export const Deals = [
  {
    id: 1,
    title: "Bluetooth Car Adapter",
    description: "Upgrade your ride — stream music and calls wirelessly.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629559/51ixWHI-aaL_f08rtq.jpg",
    alt: "Bluetooth adapter plugged into car dashboard",
  },
  {
    id: 2,
    title: "Laptop Cooling Pad",
    description: "Keep your laptop cool during intense work.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629653/71t9L9oIYhL._UF894_1000_QL80__ixvmga.jpg",
    alt: "Laptop cooling pad with LED fans",
  },
  {
    id: 3,
    title: "Smart LED Light Strip",
    description: "Transform your room — colors that follow music.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629708/e41bf895aae6fa9adfeb14a865f33d5b939e2ccf_c2xbo2.jpg",
    alt: "Smart LED light strip glowing in multiple colors",
  },
  {
    id: 4,
    title: "Wireless Gaming Controller",
    description: "Next-gen control, cross-platform ready.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632336/RGB-Wireless-Gaming-Controller-P05-PS4-Nintendo-Switch-21112022-01-p_m0kq6n.jpg",
    alt: "Wireless gaming controller for console and PC",
  },
  {
    id: 5,
    title: "Smart Security Camera",
    description: "Home security made simple — 25% off today.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632804/maxresdefault_rfv11r.jpg",
    alt: "Indoor smart security camera with night vision",
  },
  {
    id: 6,
    title: "Portable Power Bank",
    description: "Charge anywhere — fast and reliable backup.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632834/71vk828YYjL._UF894_1000_QL80__kxnwmc.jpg",
    alt: "Portable power bank charging phone",
  },
  {
    id: 7,
    title: "Smart Projector Mini",
    description: "Compact projector perfect for movies.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632884/oji-mini-Portable-Projector-tripod_fjy44x.jpg",
    alt: "Mini projector displaying on wall",
  },
  {
    id: 8,
    title: "Gaming Mouse Elite",
    description: "Precision clicks with RGB — now 20% off.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633065/61YTpIudkeL_icpjvg.jpg",
    alt: "RGB gaming mouse with customizable buttons",
  },
  {
    id: 9,
    title: "Smart Fitness Band",
    description: "Track steps, sleep, and heart rate on sale.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633080/71vEE2i4QIL._UF894_1000_QL80__n2qved.jpg",
    alt: "Fitness tracker showing steps and heart rate",
  },
  {
    id: 10,
    title: "Noise Cancelling Earbuds",
    description: "Save 30% — pure sound, no distractions.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633128/513NQdmdMXL._UF894_1000_QL80__hucjvs.jpg",
    alt: "Wireless earbuds with active noise cancellation",
  },
];
