export const differentProducts = [
  {
    id: 1,
    title: "UltraSlim Laptop X13",
    description: "Lightweight laptop with high-speed performance and all-day battery life.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629653/71t9L9oIYhL._UF894_1000_QL80__ixvmga.jpg",
    alt: "Slim laptop with backlit keyboard",
    category: "Computing & Tablets",
    price: "$899",
    details: "Overview: The UltraSlim Laptop X13 is engineered for professionals and students on the move, combining powerful internals with a featherlight, durable chassis that withstands the rigors of daily travel while delivering exceptional performance.",
        
  },
  {
    id: 2,
    title: "Pro Tablet 11 Max",
    description: "A versatile tablet perfect for work, drawing, and entertainment.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629559/51ixWHI-aaL_f08rtq.jpg",
    alt: "Tablet with stylus on desk",
    category: "Computing & Tablets",
    price: "$649",
    details: "Overview: The Pro Tablet 11 Max blurs the line between tablet and laptop, offering a stunning 120Hz display, powerful chipset, and compatibility with a full suite of creative accessories for professionals and creatives alike.",
  },
  {
    id: 3,
    title: "Ergo Wireless Mouse",
    description: "Ergonomic mouse designed for smooth and silent clicks.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633065/61YTpIudkeL_icpjvg.jpg",
    alt: "Ergonomic mouse with RGB lighting",
    category: "Computing & Tablets",
    price: "$59",
    details: "Overview: Say goodbye to wrist strain with this vertically designed ergonomic mouse that promotes a natural handshake grip, reducing pressure on your wrist and forearm during long work sessions with near-silent clicking.",
        
  },
  {
    id: 4,
    title: "Mechanical Keyboard RGB",
    description: "Tactile keys and customizable lighting for every gamer and creator.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628873/pngtree-vibrant-rgb-keyboard-design-png-image_14699987_j6yp21.png",
    alt: "RGB keyboard with backlight",
    category: "Computing & Tablets",
    price: "$129",
    details: "Overview: Elevate your typing and gaming experience with genuine mechanical switches for tactile feedback and fully customizable per-key RGB lighting that synchronizes with major games and applications for an immersive experience.",
        
  },
  {
    id: 5,
    title: "Laptop Cooling Pad Pro",
    description: "Keep your laptop cool even under heavy performance load.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629653/71t9L9oIYhL._UF894_1000_QL80__ixvmga.jpg",
    alt: "Cooling pad with blue LED fans",
    category: "Computing & Tablets",
    price: "$39",
    details: "Overview: An essential accessory for gamers and power users, this cooling pad features dual high-RPM fans that actively pull heat away from your laptop, preventing thermal throttling and maintaining peak performance during intensive tasks.",
  },
  {
    id: 6,
    title: "Wireless Charging Dock",
    description: "Charge your tablet, phone, and smartwatch simultaneously.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628872/images_z0qldl.jpg",
    alt: "Charging dock with multiple devices",
    category: "Computing & Tablets",
    price: "$89",
    details: "Overview: Declutter your desk with this 3-in-1 charging station that provides dedicated fast-charging spots for your Qi-enabled phone, compatible earbuds, and smartwatch simultaneously with a sleek, space-saving design.",
      
  },
  {
    id: 7,
    title: "Tablet Keyboard Case",
    description: "Turn your tablet into a mini laptop with detachable keyboard.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632834/71vk828YYjL._UF894_1000_QL80__kxnwmc.jpg",
    alt: "Tablet case with attached keyboard",
    category: "Computing & Tablets",
    price: "$45",
    details: "Overview: Transform your tablet into a productive laptop replacement with this versatile case featuring a detachable Bluetooth keyboard with well-spaced keys and multi-touch trackpad while providing full-body protection.",
      
  },
  {
    id: 8,
    title: "HD Webcam Pro",
    description: "1080p webcam with built-in microphone for meetings.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632804/maxresdefault_rfv11r.jpg",
    alt: "Webcam mounted on monitor",
    category: "Computing & Tablets",
    price: "$75",
    details: "Overview: Look your best in every video call with sharp, true-to-life 1080p video at 60fps, even in low-light conditions, featuring dual stereo microphones with noise reduction to ensure your voice is heard clearly.",
     
  },
  {
    id: 9,
    title: "USB-C Hub 8-in-1",
    description: "Expand your connectivity with HDMI, USB, SD, and more.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632336/RGB-Wireless-Gaming-Controller-P05-PS4-Nintendo-Switch-21112022-01-p_m0kq6n.jpg",
    alt: "USB-C Hub with multiple ports",
    category: "Computing & Tablets",
    price: "$49",
    details: "Overview: Unlock the full potential of your modern laptop with this compact adapter that instantly adds essential ports for connecting monitors, transferring files from cameras, using wired peripherals, and more through a single cable.",
      
  },
  {
    id: 10,
    title: "External SSD 1TB",
    description: "Ultra-fast portable storage for all your files and media.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633128/513NQdmdMXL._UF894_1000_QL80__hucjvs.jpg",
    alt: "Sleek silver external SSD drive",
    category: "Computing & Tablets",
    price: "$159",
    details: "Overview: Experience blistering transfer speeds with this NVMe-based external SSD in a rugged, compact chassis, perfect for storing large media libraries, editing video directly from the drive, and creating fast backups.",
      
  },
  {
    id: 11,
    title: "Smart Stylus Pen",
    description: "Precision stylus for drawing, note-taking, and design.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628876/pngimg.com_-_gopro_PNG70641_mwxyqm.png",
    alt: "Stylus pen resting beside tablet",
    category: "Computing & Tablets",
    price: "$39",
    details: "Overview: Unleash your creativity with pixel-perfect precision, palm rejection, and tilt sensitivity that feels as natural as pen on paper, ideal for artists, designers, students, and anyone who prefers handwriting.",
      
  },
  {
    id: 12,
    title: "Adjustable Laptop Stand",
    description: "Ergonomic aluminum stand for comfort and airflow.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629708/e41bf895aae6fa9adfeb14a865f33d5b939e2ccf_c2xbo2.jpg",
    alt: "Laptop stand on work desk",
    category: "Computing & Tablets",
    price: "$49",
    details: "Overview: Improve your posture and boost your laptop's cooling with this sturdy, height-adjustable stand that elevates your screen to eye level, reducing neck and back strain while promoting better air circulation.",
     
  },
  {
    id: 13,
    title: "Wireless Headphones X1",
    description: "Noise-cancelling headphones for immersive listening.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628874/pngimg.com_-_headphones_PNG101961_oahxry.png",
    alt: "Black over-ear wireless headphones",
    category: "Music Gadgets",
    price: "$199",
    details: "Overview: Immerse yourself in pure audio bliss with advanced active noise cancellation that blocks out the world, coupled with premium sound quality and exceptional comfort for long listening sessions.",
      
  },
  {
    id: 14,
    title: "Bluetooth Speaker Mini",
    description: "Portable speaker with booming sound and compact design.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628878/pngimg.com_-_wireless_speaker_PNG22_zrywut.png",
    alt: "Portable Bluetooth speaker",
    category: "Music Gadgets",
    price: "$69",
    details: "Overview: Despite its compact size, this portable speaker delivers surprisingly powerful 360-degree sound with deep bass, making it the perfect companion for outdoor adventures, parties, and travel.",

  },
  {
    id: 15,
    title: "Noise Cancelling Earbuds",
    description: "Block out distractions with immersive clarity.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633128/513NQdmdMXL._UF894_1000_QL80__hucjvs.jpg",
    alt: "Wireless earbuds",
    category: "Music Gadgets",
    price: "$149",
    details: "Overview: Experience true wireless freedom with advanced hybrid active noise cancellation that adapts to your environment, delivering crystal-clear audio and call quality in a compact, comfortable design.",

  },
  {
    id: 16,
    title: "Smart Soundbar",
    description: "Powerful soundbar with deep bass and smart controls.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628872/images_z0qldl.jpg",
    alt: "Soundbar placed below TV",
    category: "Music Gadgets",
    price: "$279",
    details: "Overview: Transform your TV viewing experience with this premium soundbar featuring Dolby Audio, built-in subwoofer for rich bass, and smart voice control compatibility for seamless integration into your entertainment system.",
  },
  {
    id: 17,
    title: "Vinyl Turntable Retro",
    description: "Classic turntable with modern Bluetooth connection.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760574927/WhatsApp_Image_2025-10-16_at_01.29.25_1cb40d4e_kjqh39.jpg",
    alt: "Vinyl turntable playing record",
    category: "Music Gadgets",
    price: "$249",
    details: "Overview: Rediscover the warm, authentic sound of vinyl with this modern turntable that combines vintage aesthetics with contemporary features like Bluetooth connectivity and built-in speakers for the best of both worlds.",
     
  },
  {
    id: 18,
    title: "Studio Microphone Set",
    description: "High-fidelity recording mic for music and podcasting.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760578649/5ab77ab3-6242-4fe0-b057-9d8eb71b0883_w600_qbgbju.jpg",
    alt: "Studio mic on adjustable stand",
    category: "Music Gadgets",
    price: "$199",
    details: "Overview: Achieve professional-grade audio recording with this complete podcasting bundle featuring a studio condenser microphone, shock mount, pop filter, and adjustable boom arm for crystal-clear vocals and instruments.",
      
  },
  {
    id: 19,
    title: "DJ Mixer Console",
    description: "Professional-grade mixer for live sessions and recording.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629559/51ixWHI-aaL_f08rtq.jpg",
    alt: "DJ console with knobs and sliders",
    category: "Music Gadgets",
    price: "$499",
    details: "Overview: Take your DJ performances to the next level with this professional 4-channel mixer featuring high-resolution color displays, multi-effects processors, and seamless software integration for both live sets and studio production.",
      
  },
  {
    id: 20,
    title: "Smart Glasses Vision",
    description: "Glasses that sync with music and phone notifications.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628872/NJYUAN-V3-Smart-Glasses-4-800x720_n9nfyx.png",
    alt: "Smart glasses with built-in speakers",
    category: "Music Gadgets",
    price: "$299",
    details: "Overview: Experience audio in a revolutionary way with these stylish smart glasses that feature open-ear speakers for immersive sound while keeping you aware of your surroundings, plus discreet notifications and voice assistant access.",
      
  },
  {
    id: 21,
    title: "Bass Booster Headset",
    description: "Rich, deep sound experience with comfortable design.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628874/pngimg.com_-_headphones_PNG101961_oahxry.png",
    alt: "Bass-heavy over-ear headphones",
    category: "Music Gadgets",
    price: "$129",
    details: "Overview: Designed for bass lovers, these headphones deliver powerful, punchy low frequencies without sacrificing clarity in mids and highs, featuring extra-large drivers and enhanced bass ports for an immersive listening experience.",
      
  },
  {
    id: 22,
    title: "Smart Bluetooth Cap",
    description: "Hat with built-in speakers and mic for wireless calls.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633080/71vEE2i4QIL._UF894_1000_QL80__n2qved.jpg",
    alt: "Cap with hidden Bluetooth module",
    category: "Music Gadgets",
    price: "$79",
    details: "Overview: The ultimate fusion of fashion and technology, this smart cap features discreet built-in bone conduction speakers in the brim and a microphone for hands-free calls and music while maintaining a completely normal appearance.",
      
  },
  {
    id: 23,
    title: "Wireless Karaoke Mic",
    description: "Sing anywhere — fun for parties and travel.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632884/oji-mini-Portable-Projector-tripod_fjy44x.jpg",
    alt: "Wireless karaoke microphone",
    category: "Music Gadgets",
    price: "$89",
    details: "Overview: Turn any space into a karaoke stage with this all-in-one wireless microphone featuring built-in speakers, multiple voice effects, echo control, and Bluetooth connectivity for backing tracks from your phone.",
    
  },
  {
    id: 24,
    title: "Smart LED Speaker",
    description: "Light-up speaker that dances to your favorite beats.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629708/e41bf895aae6fa9adfeb14a865f33d5b939e2ccf_c2xbo2.jpg",
    alt: "Colorful LED Bluetooth speaker",
    category: "Music Gadgets",
    price: "$99",
    details: "Overview: Create an immersive audio-visual experience with this smart speaker featuring 360-degree RGB LED lights that sync to your music's rhythm, multiple lighting modes, and surprisingly powerful sound for its size.",
     
  },
  {
    id: 25,
    title: "4K Action Camera Pro",
    description: "Capture adventures in ultra-HD clarity.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628876/pngimg.com_-_gopro_PNG70641_mwxyqm.png",
    alt: "Compact 4K action camera",
    category: "Camera & Lenses",
    price: "$249",
    details: "Overview: Built for adventurers, this rugged 4K action camera captures stunning stabilized footage in any condition with advanced electronic image stabilization, waterproof design, and multiple mounting options for any activity.",
      
  },
  {
    id: 26,
    title: "Drone Aerial Pro",
    description: "Fly high and capture cinematic aerial footage.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628880/Drone-PNG-Image-Background_se8kxw.png",
    alt: "Professional drone flying over field",
    category: "Camera & Lenses",
    price: "$599",
    details: "Overview: Capture breathtaking aerial cinematography with this professional drone featuring a 4K camera on a 3-axis gimbal, GPS follow-me mode, obstacle avoidance, and up to 30 minutes of flight time for stunning overhead perspectives.",
      
  },
  {
    id: 27,
    title: "Smart Security Camera",
    description: "Keep your home secure — night vision and app control.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632804/maxresdefault_rfv11r.jpg",
    alt: "Security camera mounted indoors",
    category: "Camera & Lenses",
    price: "$129",
    details: "Overview: Monitor your home 24/7 with this smart security camera featuring 1080p HD video, color night vision, two-way audio, person detection, and seamless integration with your smart home ecosystem for complete peace of mind.",
     
  },
  {
    id: 28,
    title: "Tripod Stand Pro",
    description: "Stable and extendable tripod for cameras and phones.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632884/oji-mini-Portable-Projector-tripod_fjy44x.jpg",
    alt: "Camera tripod stand",
    category: "Camera & Lenses",
    price: "$59",
    details: "Overview: Achieve rock-solid stability for your photography and videography with this professional aluminum tripod featuring quick-release plates, multi-angle center column, and reversible legs for low-angle shots.",
  
  },
  {
    id: 29,
    title: "Ring Light with Mount",
    description: "Perfect for creators and video calls.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633128/513NQdmdMXL._UF894_1000_QL80__hucjvs.jpg",
    alt: "LED ring light setup",
    category: "Camera & Lenses",
    price: "$79",
    details: "Overview: Create professional-quality lighting for streaming, video calls, and content creation with this complete ring light kit featuring adjustable color temperature, brightness control, and versatile mounting options.",
     
  },
  {
    id: 30,
    title: "Camera Lens Kit",
    description: "Get creative with wide, macro, and zoom lenses.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629708/e41bf895aae6fa9adfeb14a865f33d5b939e2ccf_c2xbo2.jpg",
    alt: "Assorted camera lenses",
    category: "Camera & Lenses",
    price: "$199",
    details: "Overview: Expand your creative possibilities with this comprehensive 3-in-1 lens kit featuring wide-angle, macro, and telephoto attachments that easily clip onto your smartphone or compatible cameras for professional results.",
    
  },
  {
    id: 31,
    title: "Camera Backpack Pro",
    description: "Protect your gear with padded compartments.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629559/51ixWHI-aaL_f08rtq.jpg",
    alt: "Camera backpack with gear",
    category: "Camera & Lenses",
    price: "$89",
    details: "Overview: Safely transport and organize all your photography equipment with this professional camera backpack featuring customizable padded dividers, weather-resistant construction, and dedicated compartments for laptops and accessories.",
     
  },
  {
    id: 32,
    title: "Wireless Remote Shutter",
    description: "Take photos hands-free with Bluetooth connection.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633065/61YTpIudkeL_icpjvg.jpg",
    alt: "Small Bluetooth camera remote",
    category: "Camera & Lenses",
    price: "$25",
    details: "Overview: Eliminate camera shake and capture perfect group photos with this compact Bluetooth remote shutter that works with smartphones, DSLRs, and mirrorless cameras from up to 30 feet away.",
     
  },
  {
    id: 33,
    title: "Camera Cleaning Kit",
    description: "Everything you need to keep your lenses spotless.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632834/71vk828YYjL._UF894_1000_QL80__kxnwmc.jpg",
    alt: "Lens cleaning tools and cloths",
    category: "Camera & Lenses",
    price: "$29",
    details: "Overview: Maintain your valuable camera equipment in pristine condition with this professional 12-piece cleaning kit featuring lens pens, microfiber cloths, cleaning solution, and specialized tools for sensors and delicate surfaces.",
  },
  {
    id: 34,
    title: "Action Cam Mount Set",
    description: "Attach your action cam anywhere safely.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628876/pngimg.com_-_gopro_PNG70641_mwxyqm.png",
    alt: "Set of camera mounts",
    category: "Camera & Lenses",
    price: "$49",
    details: "Overview: Capture unique perspectives with this comprehensive 15-piece mounting kit designed for action cameras, featuring suction cups, helmet mounts, chest harness, and various adapters for any adventure scenario.",
      
  },
  {
    id: 35,
    title: "Mini Portable Projector",
    description: "Bring movie magic to any wall with this pocket-sized projector.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632884/oji-mini-Portable-Projector-tripod_fjy44x.jpg",
    alt: "Mini projector on tripod",
    category: "Camera & Lenses",
    price: "$299",
    details: "Overview: Transform any surface into a 100-inch cinema with this ultra-portable smart projector featuring built-in Android TV, Wi-Fi connectivity, and surprisingly bright LED projection in a compact, travel-friendly design.",
    
  },
  {
    id: 36,
    title: "Smart Gimbal Stabilizer",
    description: "Shoot smooth cinematic videos effortlessly.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629708/e41bf895aae6fa9adfeb14a865f33d5b939e2ccf_c2xbo2.jpg",
    alt: "Handheld gimbal stabilizer for camera",
    category: "Camera & Lenses",
    price: "$179",
    details: "Overview: Achieve Hollywood-quality smooth footage with this 3-axis motorized gimbal stabilizer that automatically counteracts shakes and jitters, featuring multiple follow modes, object tracking, and intuitive controls.",
      
  },
  {
    id: 37,
    title: "Smart Home Hub Pro",
    description: "Voice-controlled hub for managing all your devices.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628872/images_z0qldl.jpg",
    alt: "Smart home hub on desk",
    category: "Smart Home & Accessories",
    price: "$149",
    details: "Overview: Serve as the central brain of your smart home ecosystem, this hub connects and coordinates all your compatible devices with support for multiple protocols and built-in voice assistant for seamless control.",
      
  },
  {
    id: 38,
    title: "Smart LED Bulb Set",
    description: "Color-changing bulbs controllable via app or voice.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632804/maxresdefault_rfv11r.jpg",
    alt: "Colorful smart bulbs",
    category: "Smart Home & Accessories",
    price: "$39",
    details: "Overview: Transform your home's ambiance with this 4-pack of Wi-Fi enabled smart bulbs featuring 16 million colors, tunable white light, scheduling capabilities, and compatibility with all major voice assistants.",
     
  },
  {
    id: 39,
    title: "Smart Plug Mini",
    description: "Automate any appliance with voice or app control.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633128/513NQdmdMXL._UF894_1000_QL80__hucjvs.jpg",
    alt: "Smart plug adapter",
    category: "Smart Home & Accessories",
    price: "$29",
    details: "Overview: Instantly make any appliance smart with this compact Wi-Fi plug that allows you to control lamps, fans, and electronics remotely via app or voice, with energy monitoring and scheduling features.",
     
  },
  {
    id: 40,
    title: "Smart Doorbell Cam",
    description: "HD video doorbell with two-way audio and alerts.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629559/51ixWHI-aaL_f08rtq.jpg",
    alt: "Smart doorbell camera",
    category: "Smart Home & Accessories",
    price: "$179",
    details: "Overview: See, hear, and speak to visitors from anywhere with this advanced video doorbell featuring 1536p HD video, package detection, advanced motion detection, and weather-resistant construction.",
    
  },
  {
    id: 41,
    title: "Air Purifier SmartSense",
    description: "Cleans air efficiently with smart monitoring.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629708/e41bf895aae6fa9adfeb14a865f33d5b939e2ccf_c2xbo2.jpg",
    alt: "White air purifier device",
    category: "Smart Home & Accessories",
    price: "$199",
    details: "Overview: Breathe easier with this smart air purifier that automatically detects and removes allergens, pollutants, and odors while providing real-time air quality reports and voice control compatibility.",
  },
  {
    id: 42,
    title: "Robot Vacuum X1",
    description: "Auto-cleaning vacuum with mapping and scheduling.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632336/RGB-Wireless-Gaming-Controller-P05-PS4-Nintendo-Switch-21112022-01-p_m0kq6n.jpg",
    alt: "Smart robotic vacuum cleaner",
    category: "Smart Home & Accessories",
    price: "$349",
    details: "Overview: Keep your floors effortlessly clean with this intelligent robot vacuum featuring LiDAR navigation for precise mapping, auto-empty station, mopping capability, and voice control integration.",
  },
  {
    id: 43,
    title: "Smart Curtain Motor",
    description: "Automate your curtains with app and remote control.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633065/61YTpIudkeL_icpjvg.jpg",
    alt: "Smart curtain automation motor",
    category: "Smart Home & Accessories",
    price: "$129",
    details: "Overview: Transform your existing curtains into smart window treatments with this easy-to-install motor that enables automatic opening/closing based on schedules, sun position, or voice commands.",
    
  },
  {
    id: 44,
    title: "Smart Thermostat Pro",
    description: "Regulate home temperature efficiently with AI learning.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632884/oji-mini-Portable-Projector-tripod_fjy44x.jpg",
    alt: "Smart thermostat on wall",
    category: "Smart Home & Accessories",
    price: "$229",
    details: "Overview: Save energy and stay comfortable with this learning thermostat that automatically adapts to your schedule, provides energy usage reports, and can be controlled from anywhere via smartphone app.",
    
  },
  {
    id: 45,
    title: "Smart Aroma Diffuser",
    description: "Relax with soothing scents and mood lighting.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632834/71vk828YYjL._UF894_1000_QL80__kxnwmc.jpg",
    alt: "Smart diffuser emitting mist",
    category: "Smart Home & Accessories",
    price: "$69",
    details: "Overview: Create the perfect ambiance with this Wi-Fi enabled aroma diffuser featuring customizable LED mood lighting, adjustable mist output, scheduling capabilities, and compatibility with essential oils.",
      
  },
  {
    id: 46,
    title: "Smart Alarm Clock",
    description: "Wake up with customizable lights and sounds.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629653/71t9L9oIYhL._UF894_1000_QL80__ixvmga.jpg",
    alt: "Smart alarm clock with LED display",
    category: "Smart Home & Accessories",
    price: "$89",
    details: "Overview: Transform your wake-up routine with this smart alarm clock featuring simulated sunrise, customizable nature sounds, sleep tracking, and integration with your smart home for a gentle, natural awakening.",
     
  },
  {
    id: 47,
    title: "Home Security Kit",
    description: "Complete motion and window sensors with mobile alerts.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628873/pngtree-vibrant-rgb-keyboard-design-png-image_14699987_j6yp21.png",
    alt: "Smart security sensors kit",
    category: "Smart Home & Accessories",
    price: "$199",
    details: "Overview: Protect your home with this comprehensive DIY security system featuring door/window sensors, motion detectors, and a hub that provides professional monitoring options and instant mobile alerts.",
  
  },
  {
    id: 48,
    title: "Voice Assistant Speaker",
    description: "Your AI-powered assistant with superior audio.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628878/pngimg.com_-_wireless_speaker_PNG22_zrywut.png",
    alt: "Voice assistant smart speaker",
    category: "Smart Home & Accessories",
    price: "$149",
    details: "Overview: Enjoy premium sound quality combined with advanced voice assistant capabilities in this smart speaker that serves as both an entertainment hub and smart home controller with far-field voice recognition.",
      
  },
  {
    id: 49,
    title: "4K Ultra HD Smart TV 55”",
    description: "Cinematic visuals with HDR and built-in streaming apps.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632884/oji-mini-Portable-Projector-tripod_fjy44x.jpg",
    alt: "Smart 4K television on wall",
    category: "TV & Home Appliances",
    price: "$699",
    details: "Overview: Immerse yourself in breathtaking 4K entertainment with this feature-packed smart TV featuring Quantum Dot technology for vibrant colors, Dolby Vision HDR, and a powerful smart platform with all major streaming services.",
   
  },
  {
    id: 50,
    title: "Mini Projector Pro",
    description: "Compact projector with Wi-Fi and Bluetooth support.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632804/maxresdefault_rfv11r.jpg",
    alt: "Mini projector with tripod",
    category: "TV & Home Appliances",
    price: "$299",
    details: "Overview: Create a big-screen experience anywhere with this ultra-portable smart projector featuring native 1080p resolution, built-in Android TV, auto keystone correction, and surprisingly powerful speakers in a compact design.",
     
  },
  {
    id: 51,
    title: "Smart Refrigerator Touch",
    description: "Wi-Fi enabled fridge with smart display and camera.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629559/51ixWHI-aaL_f08rtq.jpg",
    alt: "Smart refrigerator with touchscreen",
    category: "TV & Home Appliances",
    price: "$1,299",
    details: "Overview: Revolutionize your kitchen with this French door smart refrigerator featuring a large interactive touchscreen, internal cameras to see contents remotely, voice control, and family organization features.",
     
  },
  {
    id: 52,
    title: "Washing Machine TurboWash",
    description: "Energy-efficient washer with multiple smart modes.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629708/e41bf895aae6fa9adfeb14a865f33d5b939e2ccf_c2xbo2.jpg",
    alt: "Modern washing machine",
    category: "TV & Home Appliances",
    price: "$899",
    details: "Overview: Experience the future of laundry with this smart front-load washer featuring TurboWash technology that cleans full loads in just 30 minutes, steam sanitization, and remote control via smartphone app.",
      
  },
  {
    id: 53,
    title: "Microwave Oven SmartHeat",
    description: "Sensor cooking and voice-enabled commands.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633128/513NQdmdMXL._UF894_1000_QL80__hucjvs.jpg",
    alt: "Smart microwave oven",
    category: "TV & Home Appliances",
    price: "$279",
    details: "Overview: Simplify meal preparation with this smart over-the-range microwave featuring sensor cooking technology that automatically adjusts time and power, voice control compatibility, and built-in ventilation system.",
     
  },
  {
    id: 54,
    title: "Air Conditioner CoolMax",
    description: "Quiet, energy-efficient cooling with smart temperature control.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633065/61YTpIudkeL_icpjvg.jpg",
    alt: "Wall-mounted air conditioner",
    category: "TV & Home Appliances",
    price: "$649",
    details: "Overview: Stay comfortably cool with this ultra-quiet smart inverter air conditioner featuring Wi-Fi connectivity for remote control, energy-saving modes, and precise temperature maintenance with minimal noise disruption.",
     
  },
  {
    id: 55,
    title: "Smart Ceiling Fan AirFlow",
    description: "App-controlled ceiling fan with mood lighting.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632834/71vk828YYjL._UF894_1000_QL80__kxnwmc.jpg",
    alt: "Smart ceiling fan",
    category: "TV & Home Appliances",
    price: "$229",
    details: "Overview: Enhance your home's comfort and ambiance with this smart ceiling fan featuring integrated dimmable LED lighting, reversible blades for seasonal use, and full app and voice control capabilities.",
     
  },
  {
    id: 56,
    title: "Home Theater Soundbar Set",
    description: "Dolby surround system for immersive audio.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628878/pngimg.com_-_wireless_speaker_PNG22_zrywut.png",
    alt: "Soundbar with subwoofer",
    category: "TV & Home Appliances",
    price: "$499",
    details: "Overview: Transform your living room into a cinematic experience with this complete 5.1.2 channel Dolby Atmos soundbar system featuring wireless subwoofer, rear satellite speakers, and upward-firing drivers for true overhead sound.",

  },
  {
    id: 57,
    title: "Smart Vacuum Cleaner",
    description: "Auto-clean with voice and schedule support.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628872/images_z0qldl.jpg",
    alt: "Robot vacuum cleaner",
    category: "TV & Home Appliances",
    price: "$399",
    details: "Overview: Maintain pristine floors effortlessly with this advanced robot vacuum featuring LiDAR navigation for efficient cleaning paths, self-emptying base, mopping capability, and comprehensive smart home integration.",

  },
  {
    id: 58,
    title: "Air Fryer XL Touch",
    description: "Smart touchscreen fryer for healthy cooking.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629708/e41bf895aae6fa9adfeb14a865f33d5b939e2ccf_c2xbo2.jpg",
    alt: "Digital air fryer",
    category: "TV & Home Appliances",
    price: "$159",
    details: "Overview: Enjoy crispy, delicious fried foods with up to 75% less fat using this large-capacity smart air fryer featuring digital touchscreen controls, preset cooking programs, and Wi-Fi connectivity for remote monitoring.",
      
  },
  {
    id: 59,
    title: "Smart Humidifier Breeze",
    description: "App-controlled air humidifier with LED lights.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629653/71t9L9oIYhL._UF894_1000_QL80__ixvmga.jpg",
    alt: "Smart humidifier",
    category: "TV & Home Appliances",
    price: "$99",
    details: "Overview: Maintain optimal humidity levels for health and comfort with this smart humidifier featuring app and voice control, essential oil diffusion, color-changing mood lighting, and automatic humidity sensing.",
     
  },
  {
    id: 60,
    title: "Compact Dishwasher SmartWash",
    description: "Energy-efficient and whisper-quiet dishwasher.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632336/RGB-Wireless-Gaming-Controller-P05-PS4-Nintendo-Switch-21112022-01-p_m0kq6n.jpg",
    alt: "Compact dishwasher on counter",
    category: "TV & Home Appliances",
    price: "$549",
    details: "Overview: Perfect for small kitchens and households, this 18-inch smart dishwasher delivers full-size cleaning performance with ultra-quiet operation, Wi-Fi connectivity, and specialized cycles for every need.",
   
  },
  {
    id: 61,
    title: "Noise Cancelling Headphones Pro",
    description: "Block distractions with active noise control and deep bass.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628874/pngimg.com_-_headphones_PNG101961_oahxry.png",
    alt: "Over-ear noise cancelling headphones",
    category: "Audio Gadgets",
    price: "$249",
    details: "Overview: Immerse yourself in pure audio with industry-leading noise cancellation technology that adapts to your environment, coupled with premium drivers for rich, detailed sound and all-day comfort.",
      
  },
  {
    id: 62,
    title: "Bluetooth Speaker MaxBass",
    description: "Portable speaker with 360° sound and 12-hour battery life.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628878/pngimg.com_-_wireless_speaker_PNG22_zrywut.png",
    alt: "Portable Bluetooth speaker",
    category: "Audio Gadgets",
    price: "$129",
    details: "Overview: Experience powerful, room-filling sound from this portable speaker featuring dual passive radiators for deep bass, 360-degree audio projection, and rugged, waterproof design for any adventure.",
    
  },
  {
    id: 63,
    title: "Studio Microphone Kit",
    description: "Professional condenser mic for podcasting and recording.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628876/pngimg.com_-_gopro_PNG70641_mwxyqm.png",
    alt: "Studio microphone and stand",
    category: "Audio Gadgets",
    price: "$179",
    details: "Overview: Achieve broadcast-quality audio with this complete podcasting bundle featuring a large-diaphragm condenser microphone, shock mount, pop filter, and professional boom arm for crystal-clear recordings.",
    
  },
  {
    id: 64,
    title: "Wireless Earbuds Lite",
    description: "Compact and sweat-resistant earbuds with clear audio.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628873/pngtree-vibrant-rgb-keyboard-design-png-image_14699987_j6yp21.png",
    alt: "Wireless earbuds with case",
    category: "Audio Gadgets",
    price: "$79",
    details:"Overview: Enjoy true wireless freedom with these lightweight earbuds featuring secure-fit design for active lifestyles, clear call quality, and reliable connectivity in a compact, pocket-friendly charging case.",

  },
  {
    id: 65,
    title: "Soundbar 5.1 Surround",
    description: "Powerful surround sound with HDMI and Bluetooth.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633065/61YTpIudkeL_icpjvg.jpg",
    alt: "Soundbar under TV",
    category: "Audio Gadgets",
    price: "$399",
    details: "Overview: Transform your TV audio with this complete 5.1 channel soundbar system featuring Dolby Audio, wireless subwoofer, rear satellite speakers, and multiple connectivity options for an immersive home theater experience.",
      
  },
  {
    id: 66,
    title: "Turntable Retro Vinyl",
    description: "Classic vinyl record player with modern Bluetooth output.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632834/71vk828YYjL._UF894_1000_QL80__kxnwmc.jpg",
    alt: "Turntable playing record",
    category: "Audio Gadgets",
    price: "$229",
    details: "Overview: Experience the warm, authentic sound of vinyl with this modern turntable that blends vintage aesthetics with contemporary features like Bluetooth connectivity, built-in speakers, and USB recording capability.",
     
  },
  {
    id: 67,
    title: "Smart Home Speaker Duo",
    description: "Twin AI-powered speakers for stereo smart control.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628872/images_z0qldl.jpg",
    alt: "Pair of smart speakers",
    category: "Audio Gadgets",
    price: "$199",
    details: "Overview: Create a rich stereo soundstage with this pair of smart speakers featuring advanced voice recognition, premium audio quality, and seamless integration as the control center for your smart home ecosystem.",
      
  },
  {
    id: 68,
    title: "Clip-on Lavalier Mic",
    description: "Compact mic for interviews and content creation.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633128/513NQdmdMXL._UF894_1000_QL80__hucjvs.jpg",
    alt: "Clip-on microphone",
    category: "Audio Gadgets",
    price: "$59",
    details: "Overview: Achieve professional-quality audio for videos, podcasts, and interviews with this compact lavalier microphone featuring omnidirectional pickup, windscreen, and universal compatibility with smartphones and cameras.",
      
  },
  {
    id: 69,
    title: "Bluetooth Receiver Pro",
    description: "Add wireless streaming to any wired audio system.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632884/oji-mini-Portable-Projector-tripod_fjy44x.jpg",
    alt: "Bluetooth audio receiver",
    category: "Audio Gadgets",
    price: "$49",
    details: 
      "Overview: Modernize your existing audio equipment by adding high-quality Bluetooth connectivity to speakers, stereos, and cars with this compact receiver featuring aptX HD support for superior audio quality.",
  },
  {
    id: 70,
    title: "Conference Speaker Mic",
    description: "All-in-one speaker and mic for meetings and calls.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632804/maxresdefault_rfv11r.jpg",
    alt: "Conference speakerphone device",
    category: "Audio Gadgets",
    price: "$149",
    details: "Overview: Elevate your conference calls with this professional speakerphone featuring 360-degree microphone pickup, noise cancellation, and exceptional audio quality for crystal-clear meetings from anywhere.",
  },
  {
    id: 71,
    title: "Wireless Headset BoomMic",
    description: "Perfect for work calls and gaming with crystal clarity.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629653/71t9L9oIYhL._UF894_1000_QL80__ixvmga.jpg",
    alt: "Wireless headset with mic boom",
    category: "Audio Gadgets",
    price: "$119",
    details: 
      "Overview: Stay connected with exceptional audio quality for both listening and speaking with this wireless headset featuring a noise-cancelling boom microphone, all-day comfort, and multi-device connectivity.",
      
  },
  {
    id: 72,
    title: "Portable Karaoke Mic",
    description: "Fun wireless karaoke microphone with echo control.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629559/51ixWHI-aaL_f08rtq.jpg",
    alt: "Portable karaoke microphone",
    category: "Audio Gadgets",
    price: "$89",
    details: 
      "Overview: Turn any gathering into a karaoke party with this all-in-one wireless microphone featuring built-in speakers, multiple voice effects, adjustable echo, and Bluetooth connectivity for backing tracks.",
    
  }
];