export const differentProducts = [

  {
    id: 1,
    title: "UltraSlim Laptop X13",
    description: "Lightweight laptop with high-speed performance and all-day battery life.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629653/71t9L9oIYhL._UF894_1000_QL80__ixvmga.jpg",
    alt: "Slim laptop with backlit keyboard",
    category: "Computing & Tablets",
    price: "$899",
  },
  {
    id: 2,
    title: "Pro Tablet 11 Max",
    description: "A versatile tablet perfect for work, drawing, and entertainment.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629559/51ixWHI-aaL_f08rtq.jpg",
    alt: "Tablet with stylus on desk",
    category: "Computing & Tablets",
    price: "$649",
  },
  {
    id: 3,
    title: "Ergo Wireless Mouse",
    description: "Ergonomic mouse designed for smooth and silent clicks.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633065/61YTpIudkeL_icpjvg.jpg",
    alt: "Ergonomic mouse with RGB lighting",
    category: "Computing & Tablets",
    price: "$59",
  },
  {
    id: 4,
    title: "Mechanical Keyboard RGB",
    description: "Tactile keys and customizable lighting for every gamer and creator.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628873/pngtree-vibrant-rgb-keyboard-design-png-image_14699987_j6yp21.png",
    alt: "RGB keyboard with backlight",
    category: "Computing & Tablets",
    price: "$129",
  },
  {
    id: 5,
    title: "Laptop Cooling Pad Pro",
    description: "Keep your laptop cool even under heavy performance load.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629653/71t9L9oIYhL._UF894_1000_QL80__ixvmga.jpg",
    alt: "Cooling pad with blue LED fans",
    category: "Computing & Tablets",
    price: "$39",
  },
  {
    id: 6,
    title: "Wireless Charging Dock",
    description: "Charge your tablet, phone, and smartwatch simultaneously.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628872/images_z0qldl.jpg",
    alt: "Charging dock with multiple devices",
    category: "Computing & Tablets",
    price: "$89",
  },
  {
    id: 7,
    title: "Tablet Keyboard Case",
    description: "Turn your tablet into a mini laptop with detachable keyboard.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632834/71vk828YYjL._UF894_1000_QL80__kxnwmc.jpg",
    alt: "Tablet case with attached keyboard",
    category: "Computing & Tablets",
    price: "$45",
  },
  {
    id: 8,
    title: "HD Webcam Pro",
    description: "1080p webcam with built-in microphone for meetings.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632804/maxresdefault_rfv11r.jpg",
    alt: "Webcam mounted on monitor",
    category: "Computing & Tablets",
    price: "$75",
  },
  {
    id: 9,
    title: "USB-C Hub 8-in-1",
    description: "Expand your connectivity with HDMI, USB, SD, and more.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632336/RGB-Wireless-Gaming-Controller-P05-PS4-Nintendo-Switch-21112022-01-p_m0kq6n.jpg",
    alt: "USB-C Hub with multiple ports",
    category: "Computing & Tablets",
    price: "$49",
  },
  {
    id: 10,
    title: "External SSD 1TB",
    description: "Ultra-fast portable storage for all your files and media.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633128/513NQdmdMXL._UF894_1000_QL80__hucjvs.jpg",
    alt: "Sleek silver external SSD drive",
    category: "Computing & Tablets",
    price: "$159",
  },
  {
    id: 11,
    title: "Smart Stylus Pen",
    description: "Precision stylus for drawing, note-taking, and design.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628876/pngimg.com_-_gopro_PNG70641_mwxyqm.png",
    alt: "Stylus pen resting beside tablet",
    category: "Computing & Tablets",
    price: "$39",
  },
  {
    id: 12,
    title: "Adjustable Laptop Stand",
    description: "Ergonomic aluminum stand for comfort and airflow.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629708/e41bf895aae6fa9adfeb14a865f33d5b939e2ccf_c2xbo2.jpg",
    alt: "Laptop stand on work desk",
    category: "Computing & Tablets",
    price: "$49",
  },


  {
    id: 13,
    title: "Wireless Headphones X1",
    description: "Noise-cancelling headphones for immersive listening.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628874/pngimg.com_-_headphones_PNG101961_oahxry.png",
    alt: "Black over-ear wireless headphones",
    category: "Music Gadgets",
    price: "$199",
  },
  {
    id: 14,
    title: "Bluetooth Speaker Mini",
    description: "Portable speaker with booming sound and compact design.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628878/pngimg.com_-_wireless_speaker_PNG22_zrywut.png",
    alt: "Portable Bluetooth speaker",
    category: "Music Gadgets",
    price: "$69",
  },
  {
    id: 15,
    title: "Noise Cancelling Earbuds",
    description: "Block out distractions with immersive clarity.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633128/513NQdmdMXL._UF894_1000_QL80__hucjvs.jpg",
    alt: "Wireless earbuds",
    category: "Music Gadgets",
    price: "$149",
  },
  {
    id: 16,
    title: "Smart Soundbar",
    description: "Powerful soundbar with deep bass and smart controls.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628872/images_z0qldl.jpg",
    alt: "Soundbar placed below TV",
    category: "Music Gadgets",
    price: "$279",
  },
  {
    id: 17,
    title: "Vinyl Turntable Retro",
    description: "Classic turntable with modern Bluetooth connection.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760574927/WhatsApp_Image_2025-10-16_at_01.29.25_1cb40d4e_kjqh39.jpg",
    alt: "Vinyl turntable playing record",
    category: "Music Gadgets",
    price: "$249",
  },
  {
    id: 18,
    title: "Studio Microphone Set",
    description: "High-fidelity recording mic for music and podcasting.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760578649/5ab77ab3-6242-4fe0-b057-9d8eb71b0883_w600_qbgbju.jpg",
    alt: "Studio mic on adjustable stand",
    category: "Music Gadgets",
    price: "$199",
  },
  {
    id: 19,
    title: "DJ Mixer Console",
    description: "Professional-grade mixer for live sessions and recording.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629559/51ixWHI-aaL_f08rtq.jpg",
    alt: "DJ console with knobs and sliders",
    category: "Music Gadgets",
    price: "$499",
  },
  {
    id: 20,
    title: "Smart Glasses Vision",
    description: "Glasses that sync with music and phone notifications.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628872/NJYUAN-V3-Smart-Glasses-4-800x720_n9nfyx.png",
    alt: "Smart glasses with built-in speakers",
    category: "Music Gadgets",
    price: "$299",
  },
  {
    id: 21,
    title: "Bass Booster Headset",
    description: "Rich, deep sound experience with comfortable design.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628874/pngimg.com_-_headphones_PNG101961_oahxry.png",
    alt: "Bass-heavy over-ear headphones",
    category: "Music Gadgets",
    price: "$129",
  },
  {
    id: 22,
    title: "Smart Bluetooth Cap",
    description: "Hat with built-in speakers and mic for wireless calls.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633080/71vEE2i4QIL._UF894_1000_QL80__n2qved.jpg",
    alt: "Cap with hidden Bluetooth module",
    category: "Music Gadgets",
    price: "$79",
  },
  {
    id: 23,
    title: "Wireless Karaoke Mic",
    description: "Sing anywhere — fun for parties and travel.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632884/oji-mini-Portable-Projector-tripod_fjy44x.jpg",
    alt: "Wireless karaoke microphone",
    category: "Music Gadgets",
    price: "$89",
  },
  {
    id: 24,
    title: "Smart LED Speaker",
    description: "Light-up speaker that dances to your favorite beats.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629708/e41bf895aae6fa9adfeb14a865f33d5b939e2ccf_c2xbo2.jpg",
    alt: "Colorful LED Bluetooth speaker",
    category: "Music Gadgets",
    price: "$99",
  },

 
  {
    id: 25,
    title: "4K Action Camera Pro",
    description: "Capture adventures in ultra-HD clarity.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628876/pngimg.com_-_gopro_PNG70641_mwxyqm.png",
    alt: "Compact 4K action camera",
    category: "Camera & Lenses",
    price: "$249",
  },
  {
    id: 26,
    title: "Drone Aerial Pro",
    description: "Fly high and capture cinematic aerial footage.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628880/Drone-PNG-Image-Background_se8kxw.png",
    alt: "Professional drone flying over field",
    category: "Camera & Lenses",
    price: "$599",
  },
  {
    id: 27,
    title: "Smart Security Camera",
    description: "Keep your home secure — night vision and app control.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632804/maxresdefault_rfv11r.jpg",
    alt: "Security camera mounted indoors",
    category: "Camera & Lenses",
    price: "$129",
  },
  {
    id: 28,
    title: "Tripod Stand Pro",
    description: "Stable and extendable tripod for cameras and phones.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632884/oji-mini-Portable-Projector-tripod_fjy44x.jpg",
    alt: "Camera tripod stand",
    category: "Camera & Lenses",
    price: "$59",
  },
  {
    id: 29,
    title: "Ring Light with Mount",
    description: "Perfect for creators and video calls.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633128/513NQdmdMXL._UF894_1000_QL80__hucjvs.jpg",
    alt: "LED ring light setup",
    category: "Camera & Lenses",
    price: "$79",
  },
  {
    id: 30,
    title: "Camera Lens Kit",
    description: "Get creative with wide, macro, and zoom lenses.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629708/e41bf895aae6fa9adfeb14a865f33d5b939e2ccf_c2xbo2.jpg",
    alt: "Assorted camera lenses",
    category: "Camera & Lenses",
    price: "$199",
  },
  {
    id: 31,
    title: "Camera Backpack Pro",
    description: "Protect your gear with padded compartments.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629559/51ixWHI-aaL_f08rtq.jpg",
    alt: "Camera backpack with gear",
    category: "Camera & Lenses",
    price: "$89",
  },
  {
    id: 32,
    title: "Wireless Remote Shutter",
    description: "Take photos hands-free with Bluetooth connection.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633065/61YTpIudkeL_icpjvg.jpg",
    alt: "Small Bluetooth camera remote",
    category: "Camera & Lenses",
    price: "$25",
  },
  {
    id: 33,
    title: "Camera Cleaning Kit",
    description: "Everything you need to keep your lenses spotless.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632834/71vk828YYjL._UF894_1000_QL80__kxnwmc.jpg",
    alt: "Lens cleaning tools and cloths",
    category: "Camera & Lenses",
    price: "$29",
  },
  {
    id: 34,
    title: "Action Cam Mount Set",
    description: "Attach your action cam anywhere safely.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628876/pngimg.com_-_gopro_PNG70641_mwxyqm.png",
    alt: "Set of camera mounts",
    category: "Camera & Lenses",
    price: "$49",
  },
  {
    id: 35,
    title: "Mini Portable Projector",
    description: "Bring movie magic to any wall with this pocket-sized projector.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632884/oji-mini-Portable-Projector-tripod_fjy44x.jpg",
    alt: "Mini projector on tripod",
    category: "Camera & Lenses",
    price: "$299",
  },
  {
    id: 36,
    title: "Smart Gimbal Stabilizer",
    description: "Shoot smooth cinematic videos effortlessly.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629708/e41bf895aae6fa9adfeb14a865f33d5b939e2ccf_c2xbo2.jpg",
    alt: "Handheld gimbal stabilizer for camera",
    category: "Camera & Lenses",
    price: "$179",
  },

  {
    id: 37,
    title: "Smart Home Hub Pro",
    description: "Voice-controlled hub for managing all your devices.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628872/images_z0qldl.jpg",
    alt: "Smart home hub on desk",
    category: "Smart Home & Accessories",
    price: "$149",
  },
  {
    id: 38,
    title: "Smart LED Bulb Set",
    description: "Color-changing bulbs controllable via app or voice.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632804/maxresdefault_rfv11r.jpg",
    alt: "Colorful smart bulbs",
    category: "Smart Home & Accessories",
    price: "$39",
  },
  {
    id: 39,
    title: "Smart Plug Mini",
    description: "Automate any appliance with voice or app control.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633128/513NQdmdMXL._UF894_1000_QL80__hucjvs.jpg",
    alt: "Smart plug adapter",
    category: "Smart Home & Accessories",
    price: "$29",
  },
  {
    id: 40,
    title: "Smart Doorbell Cam",
    description: "HD video doorbell with two-way audio and alerts.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629559/51ixWHI-aaL_f08rtq.jpg",
    alt: "Smart doorbell camera",
    category: "Smart Home & Accessories",
    price: "$179",
  },
  {
    id: 41,
    title: "Air Purifier SmartSense",
    description: "Cleans air efficiently with smart monitoring.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629708/e41bf895aae6fa9adfeb14a865f33d5b939e2ccf_c2xbo2.jpg",
    alt: "White air purifier device",
    category: "Smart Home & Accessories",
    price: "$199",
  },
  {
    id: 42,
    title: "Robot Vacuum X1",
    description: "Auto-cleaning vacuum with mapping and scheduling.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632336/RGB-Wireless-Gaming-Controller-P05-PS4-Nintendo-Switch-21112022-01-p_m0kq6n.jpg",
    alt: "Smart robotic vacuum cleaner",
    category: "Smart Home & Accessories",
    price: "$349",
  },
  {
    id: 43,
    title: "Smart Curtain Motor",
    description: "Automate your curtains with app and remote control.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633065/61YTpIudkeL_icpjvg.jpg",
    alt: "Smart curtain automation motor",
    category: "Smart Home & Accessories",
    price: "$129",
  },
  {
    id: 44,
    title: "Smart Thermostat Pro",
    description: "Regulate home temperature efficiently with AI learning.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632884/oji-mini-Portable-Projector-tripod_fjy44x.jpg",
    alt: "Smart thermostat on wall",
    category: "Smart Home & Accessories",
    price: "$229",
  },
  {
    id: 45,
    title: "Smart Aroma Diffuser",
    description: "Relax with soothing scents and mood lighting.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632834/71vk828YYjL._UF894_1000_QL80__kxnwmc.jpg",
    alt: "Smart diffuser emitting mist",
    category: "Smart Home & Accessories",
    price: "$69",
  },
  {
    id: 46,
    title: "Smart Alarm Clock",
    description: "Wake up with customizable lights and sounds.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629653/71t9L9oIYhL._UF894_1000_QL80__ixvmga.jpg",
    alt: "Smart alarm clock with LED display",
    category: "Smart Home & Accessories",
    price: "$89",
  },
  {
    id: 47,
    title: "Home Security Kit",
    description: "Complete motion and window sensors with mobile alerts.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628873/pngtree-vibrant-rgb-keyboard-design-png-image_14699987_j6yp21.png",
    alt: "Smart security sensors kit",
    category: "Smart Home & Accessories",
    price: "$199",
  },
  {
    id: 48,
    title: "Voice Assistant Speaker",
    description: "Your AI-powered assistant with superior audio.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628878/pngimg.com_-_wireless_speaker_PNG22_zrywut.png",
    alt: "Voice assistant smart speaker",
    category: "Smart Home & Accessories",
    price: "$149",
  },
  {
    id: 49,
    title: "4K Ultra HD Smart TV 55”",
    description: "Cinematic visuals with HDR and built-in streaming apps.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632884/oji-mini-Portable-Projector-tripod_fjy44x.jpg",
    alt: "Smart 4K television on wall",
    category: "TV & Home Appliances",
    price: "$699",
  },
  {
    id: 50,
    title: "Mini Projector Pro",
    description: "Compact projector with Wi-Fi and Bluetooth support.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632804/maxresdefault_rfv11r.jpg",
    alt: "Mini projector with tripod",
    category: "TV & Home Appliances",
    price: "$299",
  },
  {
    id: 51,
    title: "Smart Refrigerator Touch",
    description: "Wi-Fi enabled fridge with smart display and camera.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629559/51ixWHI-aaL_f08rtq.jpg",
    alt: "Smart refrigerator with touchscreen",
    category: "TV & Home Appliances",
    price: "$1,299",
  },
  {
    id: 52,
    title: "Washing Machine TurboWash",
    description: "Energy-efficient washer with multiple smart modes.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629708/e41bf895aae6fa9adfeb14a865f33d5b939e2ccf_c2xbo2.jpg",
    alt: "Modern washing machine",
    category: "TV & Home Appliances",
    price: "$899",
  },
  {
    id: 53,
    title: "Microwave Oven SmartHeat",
    description: "Sensor cooking and voice-enabled commands.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633128/513NQdmdMXL._UF894_1000_QL80__hucjvs.jpg",
    alt: "Smart microwave oven",
    category: "TV & Home Appliances",
    price: "$279",
  },
  {
    id: 54,
    title: "Air Conditioner CoolMax",
    description: "Quiet, energy-efficient cooling with smart temperature control.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633065/61YTpIudkeL_icpjvg.jpg",
    alt: "Wall-mounted air conditioner",
    category: "TV & Home Appliances",
    price: "$649",
  },
  {
    id: 55,
    title: "Smart Ceiling Fan AirFlow",
    description: "App-controlled ceiling fan with mood lighting.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632834/71vk828YYjL._UF894_1000_QL80__kxnwmc.jpg",
    alt: "Smart ceiling fan",
    category: "TV & Home Appliances",
    price: "$229",
  },
  {
    id: 56,
    title: "Home Theater Soundbar Set",
    description: "Dolby surround system for immersive audio.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628878/pngimg.com_-_wireless_speaker_PNG22_zrywut.png",
    alt: "Soundbar with subwoofer",
    category: "TV & Home Appliances",
    price: "$499",
  },
  {
    id: 57,
    title: "Smart Vacuum Cleaner",
    description: "Auto-clean with voice and schedule support.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628872/images_z0qldl.jpg",
    alt: "Robot vacuum cleaner",
    category: "TV & Home Appliances",
    price: "$399",
  },
  {
    id: 58,
    title: "Air Fryer XL Touch",
    description: "Smart touchscreen fryer for healthy cooking.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629708/e41bf895aae6fa9adfeb14a865f33d5b939e2ccf_c2xbo2.jpg",
    alt: "Digital air fryer",
    category: "TV & Home Appliances",
    price: "$159",
  },
  {
    id: 59,
    title: "Smart Humidifier Breeze",
    description: "App-controlled air humidifier with LED lights.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629653/71t9L9oIYhL._UF894_1000_QL80__ixvmga.jpg",
    alt: "Smart humidifier",
    category: "TV & Home Appliances",
    price: "$99",
  },
  {
    id: 60,
    title: "Compact Dishwasher SmartWash",
    description: "Energy-efficient and whisper-quiet dishwasher.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632336/RGB-Wireless-Gaming-Controller-P05-PS4-Nintendo-Switch-21112022-01-p_m0kq6n.jpg",
    alt: "Compact dishwasher on counter",
    category: "TV & Home Appliances",
    price: "$549",
  },
  {
    id: 61,
    title: "Noise Cancelling Headphones Pro",
    description: "Block distractions with active noise control and deep bass.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628874/pngimg.com_-_headphones_PNG101961_oahxry.png",
    alt: "Over-ear noise cancelling headphones",
    category: "Audio Gadgets",
    price: "$249",
  },
  {
    id: 62,
    title: "Bluetooth Speaker MaxBass",
    description: "Portable speaker with 360° sound and 12-hour battery life.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628878/pngimg.com_-_wireless_speaker_PNG22_zrywut.png",
    alt: "Portable Bluetooth speaker",
    category: "Audio Gadgets",
    price: "$129",
  },
  {
    id: 63,
    title: "Studio Microphone Kit",
    description: "Professional condenser mic for podcasting and recording.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628876/pngimg.com_-_gopro_PNG70641_mwxyqm.png",
    alt: "Studio microphone and stand",
    category: "Audio Gadgets",
    price: "$179",
  },
  {
    id: 64,
    title: "Wireless Earbuds Lite",
    description: "Compact and sweat-resistant earbuds with clear audio.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628873/pngtree-vibrant-rgb-keyboard-design-png-image_14699987_j6yp21.png",
    alt: "Wireless earbuds with case",
    category: "Audio Gadgets",
    price: "$79",
  },
  {
    id: 65,
    title: "Soundbar 5.1 Surround",
    description: "Powerful surround sound with HDMI and Bluetooth.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633065/61YTpIudkeL_icpjvg.jpg",
    alt: "Soundbar under TV",
    category: "Audio Gadgets",
    price: "$399",
  },
  {
    id: 66,
    title: "Turntable Retro Vinyl",
    description: "Classic vinyl record player with modern Bluetooth output.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632834/71vk828YYjL._UF894_1000_QL80__kxnwmc.jpg",
    alt: "Turntable playing record",
    category: "Audio Gadgets",
    price: "$229",
  },
  {
    id: 67,
    title: "Smart Home Speaker Duo",
    description: "Twin AI-powered speakers for stereo smart control.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760628872/images_z0qldl.jpg",
    alt: "Pair of smart speakers",
    category: "Audio Gadgets",
    price: "$199",
  },
  {
    id: 68,
    title: "Clip-on Lavalier Mic",
    description: "Compact mic for interviews and content creation.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760633128/513NQdmdMXL._UF894_1000_QL80__hucjvs.jpg",
    alt: "Clip-on microphone",
    category: "Audio Gadgets",
    price: "$59",
  },
  {
    id: 69,
    title: "Bluetooth Receiver Pro",
    description: "Add wireless streaming to any wired audio system.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632884/oji-mini-Portable-Projector-tripod_fjy44x.jpg",
    alt: "Bluetooth audio receiver",
    category: "Audio Gadgets",
    price: "$49",
  },
  {
    id: 70,
    title: "Conference Speaker Mic",
    description: "All-in-one speaker and mic for meetings and calls.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760632804/maxresdefault_rfv11r.jpg",
    alt: "Conference speakerphone device",
    category: "Audio Gadgets",
    price: "$149",
  },
  {
    id: 71,
    title: "Wireless Headset BoomMic",
    description: "Perfect for work calls and gaming with crystal clarity.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629653/71t9L9oIYhL._UF894_1000_QL80__ixvmga.jpg",
    alt: "Wireless headset with mic boom",
    category: "Audio Gadgets",
    price: "$119",
  },
  {
    id: 72,
    title: "Portable Karaoke Mic",
    description: "Fun wireless karaoke microphone with echo control.",
    src: "https://res.cloudinary.com/dxekfksjf/image/upload/v1760629559/51ixWHI-aaL_f08rtq.jpg",
    alt: "Portable karaoke microphone",
    category: "Audio Gadgets",
    price: "$89",
  },

];
